apiVersion: apps/v1
kind: Deployment
metadata:
  name: gauntlt-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gauntlt
  template:
    metadata:
      labels:
        app: gauntlt
    spec:
      containers:
      - name: gauntlt
        image: cithit/gauntlt:build-4
        resources:
          limits:
            memory: "6Gi"
          requests:
            memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: gauntlt-service
spec:
  selector:
    app: gauntlt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
